DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30)
);    

CREATE TABLE role(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  department_id INTEGER NOT NULL,
  FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE
);

CREATE TABLE employee(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30),
  last_name VARCHAR(30),
  role_id INTEGER NOT NULL,
  FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
  manager_id INTEGER,
  FOREIGN KEY (manager_id) REFERENCES employee (id) ON DELETE SET NULL
);
